apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-service
  labels:
    name: app
    env: prd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: app
        env: prd
    spec:
      containers:
        - name: app
          image: kissflow/app:latest
          imagePullPolicy: Always
          ports:
          - name: app-server
            containerPort: 8081
          env:
          - name: ENV
            value: test
          volumeMounts:
           - name: app-dir
             mountPath: /app
           - name: core-dir
             mountPath: /app/core
           - name: core-test-dir
             mountPath: /app/tests
      volumes:
        - name: app-dir
          hostPath:
            path: /Users/vivekmadurai/Work/kissflow-xg/app
        - name: core-dir
          hostPath:
            path: /Users/vivekmadurai/Work/kissflow-xg/ems/core
        - name: core-test-dir
          hostPath:
            path: /Users/vivekmadurai/Work/kissflow-xg/ems/tests
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    name: app
    env: prd
spec:
  type: LoadBalancer
  ports:
  # the port that this service should serve on
  - port: 8081
    targetPort: app-server
  selector:
    name: app
    env: prd