apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    name: app
    env: prd
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: app-server
  selector:
    name: app
    env: prd
