apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app-service
  labels:
    name: app
    env: prd
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: app
        env: prd
    spec:
      containers:
        - name: app
          image: gcr.io/kf3-test-sanbox/flask-uwsgi-sample:v1
          imagePullPolicy: Always
          ports:
          - name: app-server
            containerPort: 80
          env:
          - name: ENV
            value: prd
          resources: 
            requests:
              cpu: "100m"
            limits:
              cpu: "100m"
      volumes:
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
        - name: cloudsql
          emptyDir: {}
